import Head from "next/head";
import styles from "@/styles/Home.module.css";
import CatsList from "@/components/CatsList/CatsList";


export default function Home() {
  return (
    <>
      <Head>
        <title>Кошачий пинтерест</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page}`}
      >
        <main className={styles.main}>

          <h1>Кошачий пинтерест</h1>

          <CatsList />
        </main>
      </div>
    </>
  );
}
